import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import tippy from 'tippy.js';
import 'tippy.js/dist/tippy.css';
import Navbar from '@/components/Navbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Stream',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="min-w-[640px]">
                    <Navbar />
                    <main className="w-full max-w-8xl mx-auto flex items-center justify-between min-h-20 px-4">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
